import { Header } from "@/components/header"
import { Footer } from "@/components/footer"

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <Header />

      <main className="mx-auto w-full max-w-4xl px-5 pb-20 pt-12 sm:pt-14 md:px-10 md:pt-16 lg:pt-20">
        <article className="space-y-8">
          <section>
            <h1 className="text-[clamp(2.2rem,5vw,3.8rem)] font-semibold leading-[1.02] tracking-tight text-white">
              SQLBots Privacy Policy
            </h1>
            <p className="mt-4 text-sm leading-7 text-white/65">Last Updated: February 18, 2026</p>
            <p className="mt-4 text-base leading-8 text-white/75">
              This Privacy Policy explains how SQLBots ("SQLBots", "we", "us") collects, uses, shares, and protects
              information when you use our website, dashboard, APIs, and related services (collectively, the
              "Service").
            </p>
            <p className="mt-4 text-base leading-8 text-white/75">
              By using SQLBots, you agree to the practices described in this Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold tracking-tight text-white">1. What This Policy Covers</h2>
            <p className="mt-4 text-base leading-8 text-white/75">This policy covers information we collect from:</p>
            <ul className="mt-4 list-disc space-y-2 pl-5 text-base leading-8 text-white/75">
              <li>visitors to our website</li>
              <li>users who create an account</li>
              <li>users who run workflows, scans, and other features inside the Service</li>
              <li>users who contact support</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold tracking-tight text-white">2. Information We Collect</h2>

            <h3 className="mt-4 text-lg font-semibold text-white">2.1 Account information</h3>
            <p className="mt-2 text-base leading-8 text-white/75">
              When you register or use the Service, we may collect:
            </p>
            <ul className="mt-2 list-disc space-y-2 pl-5 text-base leading-8 text-white/75">
              <li>email address and account identifiers</li>
              <li>username/profile details (if provided)</li>
              <li>authentication data (e.g., hashed passwords, session tokens)</li>
            </ul>

            <h3 className="mt-5 text-lg font-semibold text-white">2.2 Billing information</h3>
            <p className="mt-2 text-base leading-8 text-white/75">
              If you purchase a plan, payments are handled by third-party payment processors.
            </p>
            <ul className="mt-2 list-disc space-y-2 pl-5 text-base leading-8 text-white/75">
              <li>We may receive billing status and transaction metadata (e.g., plan type, payment confirmation, timestamps).</li>
              <li>We typically do not store full card details on our servers.</li>
            </ul>

            <h3 className="mt-5 text-lg font-semibold text-white">2.3 Service usage and technical data</h3>
            <p className="mt-2 text-base leading-8 text-white/75">
              We collect operational data to run and secure the Service, such as:
            </p>
            <ul className="mt-2 list-disc space-y-2 pl-5 text-base leading-8 text-white/75">
              <li>IP address, device/browser information, and user-agent</li>
              <li>timestamps, pages/actions, feature usage, and performance metrics</li>
              <li>error logs, crash reports, and debugging events</li>
              <li>security telemetry (e.g., rate-limit triggers, abuse patterns)</li>
            </ul>

            <h3 className="mt-5 text-lg font-semibold text-white">2.4 Targets, inputs, and results (User Content)</h3>
            <p className="mt-2 text-base leading-8 text-white/75">
              When you submit Targets or run workflows, the Service may process and store:
            </p>
            <ul className="mt-2 list-disc space-y-2 pl-5 text-base leading-8 text-white/75">
              <li>Target URLs/domains/IPs you submit</li>
              <li>parameters, configuration options, and testing metadata</li>
              <li>response signals and verification artifacts used for confidence scoring</li>
              <li>output and results generated by the Service (e.g., findings, dumps, schemas, reports)</li>
            </ul>
            <p className="mt-4 rounded-lg border border-white/10 bg-white/[0.02] px-4 py-3 text-sm leading-7 text-white/70">
              Important: You are responsible for ensuring you have authorization to test any Target and the
              rights/lawful basis to upload or process any data.
            </p>

            <h3 className="mt-5 text-lg font-semibold text-white">2.5 Support communications</h3>
            <p className="mt-2 text-base leading-8 text-white/75">If you contact us, we may collect:</p>
            <ul className="mt-2 list-disc space-y-2 pl-5 text-base leading-8 text-white/75">
              <li>messages you send us</li>
              <li>attachments or logs you share</li>
              <li>basic metadata needed to respond (timestamps, identifiers)</li>
            </ul>

            <h3 className="mt-5 text-lg font-semibold text-white">2.6 Cookies and similar technologies</h3>
            <p className="mt-2 text-base leading-8 text-white/75">
              We use cookies/local storage (or similar) to:
            </p>
            <ul className="mt-2 list-disc space-y-2 pl-5 text-base leading-8 text-white/75">
              <li>keep you signed in and maintain sessions</li>
              <li>remember preferences</li>
              <li>help prevent abuse and protect accounts</li>
              <li>measure product performance (limited analytics)</li>
            </ul>
            <p className="mt-4 text-base leading-8 text-white/75">
              You can control cookies in your browser settings, but disabling some cookies may break login/session features.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold tracking-tight text-white">3. How We Use Information</h2>
            <p className="mt-4 text-base leading-8 text-white/75">We use collected information to:</p>
            <ul className="mt-4 list-disc space-y-2 pl-5 text-base leading-8 text-white/75">
              <li><strong>Provide the Service:</strong> operate the dashboard, run workflows, store results, and deliver features</li>
              <li><strong>Secure the platform:</strong> prevent fraud, abuse, unauthorized access, and service disruption</li>
              <li><strong>Improve performance:</strong> monitor uptime, optimize speed, fix bugs, and improve reliability</li>
              <li><strong>Support users:</strong> respond to questions and troubleshoot issues</li>
              <li><strong>Billing and account management:</strong> manage subscriptions, usage limits, and payment status</li>
              <li><strong>Compliance:</strong> meet legal obligations when required (e.g., valid law enforcement requests)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold tracking-tight text-white">4. How We Share Information</h2>
            <p className="mt-4 text-base leading-8 text-white/75">We do not sell your personal information.</p>
            <p className="mt-4 text-base leading-8 text-white/75">
              We may share information in limited situations, including:
            </p>
            <ul className="mt-4 list-disc space-y-2 pl-5 text-base leading-8 text-white/75">
              <li><strong>Service providers:</strong> hosting, storage, analytics, error monitoring, email delivery, and payment processing (only what’s necessary)</li>
              <li><strong>Security and abuse prevention:</strong> when needed to investigate fraud, misuse, or attacks on the Service</li>
              <li><strong>Legal requirements:</strong> if we believe disclosure is required by applicable law or valid legal process</li>
              <li><strong>Business transfers:</strong> if SQLBots is involved in a merger, acquisition, or asset sale (data may transfer as part of that transaction)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold tracking-tight text-white">5. Data Retention</h2>
            <p className="mt-4 text-base leading-8 text-white/75">We keep data only as long as needed for:</p>
            <ul className="mt-4 list-disc space-y-2 pl-5 text-base leading-8 text-white/75">
              <li>providing the Service (e.g., keeping your projects/results available)</li>
              <li>security and abuse prevention (e.g., logs used to detect attacks or fraud)</li>
              <li>backups and operational continuity</li>
            </ul>
            <p className="mt-4 text-base leading-8 text-white/75">
              Retention periods vary depending on data type. Some logs may be retained longer for security, auditing,
              or dispute reasons.
            </p>
            <p className="mt-4 text-base leading-8 text-white/75">
              If you delete your account (or request deletion), we will make reasonable efforts to remove your personal
              data from active systems, except where we must keep certain information for security, compliance, or
              legitimate operational needs.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold tracking-tight text-white">6. Security</h2>
            <p className="mt-4 text-base leading-8 text-white/75">
              We use reasonable technical and organizational measures to protect information, such as access controls,
              encryption in transit where applicable, and monitoring.
            </p>
            <p className="mt-4 text-base leading-8 text-white/75">
              However, no system is 100% secure. You are responsible for keeping your credentials safe and using
              strong passwords.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold tracking-tight text-white">7. Your Choices and Rights</h2>
            <p className="mt-4 text-base leading-8 text-white/75">
              Depending on your location, you may have rights to:
            </p>
            <ul className="mt-4 list-disc space-y-2 pl-5 text-base leading-8 text-white/75">
              <li>access, correct, or update your account information</li>
              <li>request deletion of your account data</li>
              <li>request an export of certain data</li>
            </ul>
            <p className="mt-4 text-base leading-8 text-white/75">You can also:</p>
            <ul className="mt-2 list-disc space-y-2 pl-5 text-base leading-8 text-white/75">
              <li>adjust cookie settings in your browser</li>
              <li>stop using the Service at any time</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold tracking-tight text-white">8. International Transfers</h2>
            <p className="mt-4 text-base leading-8 text-white/75">
              Our infrastructure or service providers may process data in multiple countries. By using SQLBots, you
              understand that your information may be transferred and processed outside your country of residence.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold tracking-tight text-white">9. Children’s Privacy</h2>
            <p className="mt-4 text-base leading-8 text-white/75">
              SQLBots is not intended for individuals under 18. We do not knowingly collect personal data from
              children.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold tracking-tight text-white">10. Changes to This Policy</h2>
            <p className="mt-4 text-base leading-8 text-white/75">
              We may update this Privacy Policy from time to time. The updated version applies when posted (or on a
              later date if stated). Continued use of the Service means you accept the updated policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold tracking-tight text-white">11. Contact</h2>
            <p className="mt-4 text-base leading-8 text-white/75">
              For any questions or concerns regarding these Terms, please contact us on Telegram. You can also contact
              us on{" "}
              <a
                href="https://discord.gg/es6vcqA5zS"
                target="_blank"
                rel="noopener noreferrer"
                className="text-white underline-offset-4 transition hover:underline"
              >
                Discord
              </a>
              .
            </p>
          </section>
        </article>
      </main>

      <Footer />
    </div>
  )
}
